server:
  port: 8762
spring:
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  rabbitmq:
    addresses: midware
    port: 5672
    username: guest
    password: guest