apiVersion: v1
kind: Service
metadata:
  name: midware
  labels:
    run: midware
spec:
  selector:
    app: midware
  ports:
  - protocol: TCP
    name: rabbitmq1
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: rabbitmq2
    port: 15672
    targetPort: 15672
  - protocol: TCP
    name: elasticsearch1
    port: 9200
    targetPort: 9200
  - protocol: TCP
    name: elasticsearch2
    port: 9300
    targetPort: 9300
  - protocol: TCP
    name: kibana
    port: 5601
    targetPort: 5601
  - protocol: TCP
    name: zipkin
    port: 9411
    targetPort: 9411
  - protocol: TCP
    name: consul
    port: 8500
    targetPort: 8500
  type: LoadBalancer