apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    name: rabbitmq1
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: rabbitmq2
    port: 15672
    targetPort: 15672
  type: LoadBalancer