apiVersion: v1
kind: Service
metadata:
  name: service-probb
  labels:
    run: service-probb
spec:
  selector:
    app: service-probb
  ports:
  - protocol: TCP
    port: 8762
    targetPort: 8762
  type: LoadBalancer